'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import {Box, useTheme} from '@mui/material'
import CustomTextField from "src/components/text-field";
import {useSettings} from "src/hooks/useSettings";
import {ReactNode} from "react";
import BlankLayout from "src/views/layouts/BlankLayout";
import Login from "src/pages/login";
import LayoutNotApp from "src/views/layouts/LayoutNotApp";

export default function Home() {
    const theme = useTheme()
    const {settings} = useSettings()
    return (
        <>
            <Head>
                <title>Mobile Shop</title>
                <meta name='description' content='Generated by create next app'/>
                <meta name='viewport' content='width=device-width, initial-scale=1'/>
                <link rel='icon' href='/favicon.ico'/>
            </Head>
        </>
    )
}

Home.getLayout = (page: ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
Home.guestGuard = true
Home.authGuard = true